
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
      - 'diy/**'
  workflow_dispatch:
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Syn upstream
      run: |
        ls

#        svn export --force https://github.com/immortalwrt/luci/trunk/applications &
#        git clone --depth 1 https://github.com/Lienol/openwrt-package &
#        git clone --depth 1 https://github.com/xiaorouji/openwrt-passwall &
#        svn export --force https://github.com/coolsnowwolf/lede/trunk/package/lean ledelean &
        
#        git_sparse_clone master "https://github.com/immortalwrt/packages" "immpackages" net/mwol net/nps net/verysync net/sub-web \
#        net/subconverter net/ngrokc net/oscam net/njitclient net/scutclient net/gost admin/bpytop libs/jpcre2 libs/rapidjson libs/libcron \
#        libs/quickjspp utils/cpulimit utils/filebrowser &
        
#        git_sparse_clone master "https://github.com/openwrt/packages" "oppackages" net/shadowsocks-libev net/https-dns-proxy net/openvpn \
#        utils/cgroupfs-mount devel/ninja &
        
#        git_sparse_clone master "https://github.com/x-wrt/com.x-wrt" "x-wrt" natflow luci-app-wizard luci-app-macvlan &
        
#        git_sparse_clone master "https://github.com/immortalwrt/immortalwrt" "immwrt" package/lean package/kernel/mt7601u-ap package/kernel/mtk-eip93 \
#        package/kernel/r8152 package/kernel/r8168 package/kernel/rtl8188eu package/kernel/rtl8812au-ac \
#        package/kernel/rtl8821cu package/kernel/rtl88x2bu
        
#        git clone --depth 1 https://github.com/garypang13/my-packages && mv -f my-packages/* ./ ; rm -Rf my-packages &
        
#        ( for ipk in $(ls applications); do
#        	if [[ $(ls -l applications/$ipk/po | wc -l) -gt 3 ]]; then
#        		rm -rf applications/$ipk
#        	fi
#        done ) &
    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0

    - name: Delete duplicated packages
      run: |
        ls
    - name: Apply patches
      run: |
        ls
    - name: Modify
      run: |
        ls

    - name: Apply
      run: |
        git add .
        git commit -m "update" || true
        git push
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
